itobj/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ItHome.as_view(), name='home'),
    path('addpost/', AddPost.as_view(), name='add_post'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('categories/<slug:cat_slug>/', ItCategory.as_view(), name='show_category'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('like/<slug:post_slug>/', like_view, name='like_post'),
]

trendingit/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from itobj.views import *
from trendingit import settings

# router = routers.DefaultRouter()
# router.register(r'itlist', ItObjectViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itobj.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    # path('api/v1/', include(router.urls)),  # http://127.0.0.1:8000/api/v1/itlist/
    path('api/v1/itlist/', ItObjectAPIList.as_view()),
    path('api/v1/itlist/<int:pk>/', ItObjectAPIUpdate.as_view()),
    path('api/v1/itdelete/<int:pk>/', ItObjectAPIDestroy.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

itobj/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class ItObject(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(blank=True)
    avatar = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    views = models.IntegerField(default=0)
    likes = models.ManyToManyField(User, related_name='blog_post')
    trending = models.IntegerField(default=0)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    # def increase_views(self):
    #     self.views += 1
    #     self.save()

    def total_likes(self):
        return self.likes.count()

    class Meta:
        verbose_name = 'IT Object'
        ordering = ['-time_update']


class Category(models.Model):
    name = models.CharField(max_length=80, db_index=True)
    slug = models.SlugField(max_length=80, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('show_category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['id']

itobj/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import *


class AddPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'Category not selected'

    class Meta:
        model = ItObject
        fields = ['title', 'slug', 'content', 'is_published', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'slug': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'URL'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Content', 'cols': 60, 'rows': 10}),
            'is_published': forms.CheckboxInput(),
            'cat': forms.Select(attrs={'class': 'form-control'})
        }


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Login'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Login'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

itobj/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics, viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.response import Response
from hitcount.views import HitCountDetailView

from .forms import *
from .models import *
from .permissions import *
from .serializers import ItObjectSerializer
from .utils import *


class ItHome(DataMixin, ListView):
    model = ItObject
    template_name = 'itobj/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='TrendingIT - trending, loved and interesting things in IT world.')
        context.update(c_def)
        return context

    def get_queryset(self):
        return ItObject.objects.filter(is_published=True).select_related('cat')


class ItCategory(DataMixin, ListView):
    model = Category
    template_name = 'itobj/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_user_context(title='TrendingIT - ' + str(c.name))
        context.update(c_def)
        return context

    def get_queryset(self):
        return ItObject.objects.filter(cat__slug=self.kwargs['cat_slug'], is_published=True).select_related('cat')


class ShowPost(DataMixin, HitCountDetailView):
    model = ItObject
    template_name = 'itobj/post.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'
    count_hit = True

    # def get_object(self, queryset=None):
    #     item = super().get_object(queryset)
    #     item.increase_views()
    #     return item

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # liked used to set heart-icon to red or grey color
        liked = False
        if self.object.likes.filter(id=self.request.user.id).exists():
            liked = True
        c_def = self.get_user_context(title=context['post'], liked=liked)
        context.update(c_def)
        return context


def like_view(request, post_slug):
    post = get_object_or_404(ItObject, slug=post_slug)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('post', args=[post_slug]))


class AddPost(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'itobj/addpost.html'
    success_url = reverse_lazy('home')
    login_url = '/admin/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Add new post')
        context.update(c_def)
        return context


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'itobj/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Registration')
        context.update(c_def)
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'itobj/login.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Login')
        context.update(c_def)
        return context

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def pageNotFound(request, exception):
    return HttpResponseNotFound("<h1>Sorry, the page is not found.</h1><p>Create page for this url.</p>")


# API VIEWS
class ItObjectAPIListPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 1000


class ItObjectAPIList(generics.ListCreateAPIView):
    queryset = ItObject.objects.all()
    serializer_class = ItObjectSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)
    pagination_class = ItObjectAPIListPagination


class ItObjectAPIUpdate(generics.RetrieveUpdateAPIView):
    queryset = ItObject.objects.all()
    serializer_class = ItObjectSerializer
    permission_classes = (IsOwnerOrReadOnly,)


class ItObjectAPIDestroy(generics.RetrieveDestroyAPIView):
    queryset = ItObject.objects.all()
    serializer_class = ItObjectSerializer
    permission_classes = (IsOwnerOrReadOnly, IsAdminUser)

itobj/templates/itobj/addpost.html
{% extends 'itobj/base.html' %}

{% block content %}

<!-- ======= Contact Section ======= -->
<section class="contact" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">
        <div class="section-title">
            <h2>{{title}}</h2>
        </div>

        <div class="section-title">
            <form action="{% url 'add_post' %}" method="post" class="php-email-form2"  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="validate">{{ form.non_field_errors }}</div>

                <div class="form-group">
                    {{ form.title }}
                    <div class="">{{ form.title.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.slug }}
                    <div class="validate">{{ form.slug.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.content }}
                    <div class="validate">{{ form.content.errors }}</div>
                </div>
                <div class="form-group">
                    <label for="{{form.is_published.id_for_label }}">Publish: </label>{{ form.is_published }}
                    <div class="validate">{{ form.is_published.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.cat }}
                    <div class="validate">{{ form.cat.errors }}</div>
                </div>
                <div class="text-center">
                    <button type="submit">Save Post</button>
                </div>
            </form>
        </div>
    </div>
</section><!-- End Contact Section -->

{% endblock %}

itobj/templates/itobj/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{{ title }}</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'itobj/img/favicon.png' %}" rel="icon">
    <link href="{% static 'itobj/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'itobj/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'itobj/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'itobj/css/style.css' %}" rel="stylesheet">

</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top ">
    <div class="container">

        <div class="logo float-left">
            <h1 class="text-light"><a href="{% url 'home' %}"><span>TrendingIT</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="{% static 'itobj/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        {% block mainmenu %}
        <nav class="nav-menu float-right d-none d-lg-block">
            <ul>
                {% for m in menu %}
                {% if m.url_name == menu_active_url %}
                <li class="active"><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% else %}
                <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% endif %}
                {% endfor %}
                {% if request.user.is_authenticated %}
                    <li><a href="#">{{ user.username }}</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}}
                    <li><a href="{% url 'register' %}">Sing up</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}}
            </ul>
        </nav><!-- .nav-menu -->
        {% endblock %}

    </div>
</header><!-- End Header -->

<main id="main">

    {% block content %}
    {% endblock %}


</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="container">
        <div class="copyright">
            <i class="icofont-toy-cat"></i> Website <a href="https://github.com/kirill0720/trending-it-django_website_api" target="_blank">repo</a>
        </div>
        <div class="credits">
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'itobj/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'itobj/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'itobj/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'itobj/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'itobj/vendor/venobox/venobox.min.js' %}"></script>
<script src="{% static 'itobj/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'itobj/vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static 'itobj/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'itobj/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'itobj/vendor/aos/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'itobj/js/main.js' %}"></script>

</body>

</html>

itobj/templates/itobj/index.html
{% extends 'itobj/base.html' %}
{% load itobj_tags %}

{% block content %}

<!-- ======= Blog Section ======= -->
<section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 entries">

                {% for p in posts %}
                <article class="entry">

                    {% show_title_stats p %}

                    <div class="entry-content">
                        <p>
                            {% autoescape off %}
                            {{p.content|truncatewords:50}}
                            {% endautoescape %}
                        </p>
                        <div class="read-more">
                            <a href="{{ p.get_absolute_url }}">Read More</a>
                        </div>
                    </div>

                </article><!-- End blog entry -->
                {% endfor %}

                {% if page_obj.has_other_pages %}
                <div class="blog-pagination">
                    <ul class="justify-content-center">
                        {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icofont-rounded-left"></i></a>
                        </li>
                        {% endif %}

                        {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                        <li class="active"><a href="#">{{ p }}</a></li>
                        {% elif p >= page_obj.number|add:-1 and p <= page_obj.number|add:1 %}
                        <li><a href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}"><i class="icofont-rounded-right"></i></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
                {% endif %}

            </div><!-- End blog entries list -->

            {% show_sidebar %}

        </div><!-- End .row -->
    </div><!-- End .container -->
</section><!-- End Blog Section -->


{% endblock %}

itobj/templates/itobj/login.html
{% extends 'itobj/base.html' %}

{% block content %}

<!-- ======= Contact Section ======= -->
<section class="contact" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">
        <div class="section-title">
            <h2>{{title}}</h2>
        </div>

        <div class="section-title">
            <form method="post" class="php-email-form2">
                {% csrf_token %}
                <div class="validate">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <div class="form-group">
                    {{ f }}
                    <div class="validate">{{ f.errors }}</div>
                </div>
                {% endfor %}

                <div class="text-center">
                    <button type="submit">Login</button>
                </div>

            </form>
        </div>
    </div>
</section><!-- End Contact Section -->

{% endblock %}

itobj/templates/itobj/post.html
{% extends 'itobj/base.html' %}
{% load itobj_tags %}

{% block content %}

<!-- ======= Blog Section ======= -->
<section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
  <div class="container">

    <div class="row">

      <div class="col-lg-8 entries">

        <article class="entry entry-single">

          {% show_title_stats post liked %}

          <div class="entry-content">
            {% autoescape off %}
            {{post.content}}
            {% endautoescape %}
          </div>

        </article><!-- End blog entry -->

      </div><!-- End blog entries list -->

      {% show_sidebar %}

    </div><!-- End row -->

  </div><!-- End container -->

</section><!-- End Blog Section -->


{% endblock %}

itobj/templates/itobj/register.html
{% extends 'itobj/base.html' %}

{% block content %}

<!-- ======= Contact Section ======= -->
<section class="contact" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">
        <div class="section-title">
            <h2>{{title}}</h2>
        </div>

        <div class="section-title">
            <form method="post" class="php-email-form2">
                {% csrf_token %}
                <div class="validate">{{ form.non_field_errors }}</div>

                {% for f in form %}
                <div class="form-group">
                    {{ f }}
                    <div class="validate">{{ f.errors }}</div>
                </div>
                {% endfor %}

                <div class="text-center">
                    <button type="submit">Register</button>
                </div>

            </form>
        </div>
    </div>
</section><!-- End Contact Section -->

{% endblock %}

itobj/templates/itobj/show_sidebar.html
<div class="col-lg-4">
    <div class="sidebar">

        <!--              <h3 class="sidebar-title">Search</h3>-->
        <!--              <div class="sidebar-item search-form">-->
        <!--                <form action="">-->
        <!--                  <input type="text">-->
        <!--                  <button type="submit"><i class="icofont-search"></i></button>-->
        <!--                </form>-->
        <!--              </div>&lt;!&ndash; End sidebar search formn&ndash;&gt;-->

        <h3 class="sidebar-title">Categories</h3>
        <div class="sidebar-item categories">
            <ul>
                {% for c in cats %}
                <li><a href="{{ c.get_absolute_url }}">{{ c.name }} <span>({{ c.itobject_set.count }})</span></a></li>
                {% endfor %}
            </ul>

        </div><!-- End sidebar categories-->

        <!--              <h3 class="sidebar-title">Recent Posts</h3>-->
        <!--              <div class="sidebar-item recent-posts">-->
        <!--                <div class="post-item clearfix">-->
        <!--                  <img src="assets/img/recent-posts-1.jpg" alt="">-->
        <!--                  <h4><a href="blog-single.html">Nihil blanditiis at in nihil autem</a></h4>-->
        <!--                  <time datetime="2020-01-01">Jan 1, 2020</time>-->
        <!--                </div>-->

        <!--                <div class="post-item clearfix">-->
        <!--                  <img src="assets/img/recent-posts-2.jpg" alt="">-->
        <!--                  <h4><a href="blog-single.html">Quidem autem et impedit</a></h4>-->
        <!--                  <time datetime="2020-01-01">Jan 1, 2020</time>-->
        <!--                </div>-->

        <!--                <div class="post-item clearfix">-->
        <!--                  <img src="assets/img/recent-posts-3.jpg" alt="">-->
        <!--                  <h4><a href="blog-single.html">Id quia et et ut maxime similique occaecati ut</a></h4>-->
        <!--                  <time datetime="2020-01-01">Jan 1, 2020</time>-->
        <!--                </div>-->

        <!--                <div class="post-item clearfix">-->
        <!--                  <img src="assets/img/recent-posts-4.jpg" alt="">-->
        <!--                  <h4><a href="blog-single.html">Laborum corporis quo dara net para</a></h4>-->
        <!--                  <time datetime="2020-01-01">Jan 1, 2020</time>-->
        <!--                </div>-->

        <!--                <div class="post-item clearfix">-->
        <!--                  <img src="assets/img/recent-posts-5.jpg" alt="">-->
        <!--                  <h4><a href="blog-single.html">Et dolores corrupti quae illo quod dolor</a></h4>-->
        <!--                  <time datetime="2020-01-01">Jan 1, 2020</time>-->
        <!--                </div>-->
        <!--              </div>&lt;!&ndash; End sidebar recent posts&ndash;&gt;-->

        <!--              <h3 class="sidebar-title">Tags</h3>-->
        <!--              <div class="sidebar-item tags">-->
        <!--                <ul>-->
        <!--                  <li><a href="#">App</a></li>-->
        <!--                  <li><a href="#">IT</a></li>-->
        <!--                  <li><a href="#">Business</a></li>-->
        <!--                  <li><a href="#">Business</a></li>-->
        <!--                  <li><a href="#">Mac</a></li>-->
        <!--                  <li><a href="#">Design</a></li>-->
        <!--                  <li><a href="#">Office</a></li>-->
        <!--                  <li><a href="#">Creative</a></li>-->
        <!--                  <li><a href="#">Studio</a></li>-->
        <!--                  <li><a href="#">Smart</a></li>-->
        <!--                  <li><a href="#">Tips</a></li>-->
        <!--                  <li><a href="#">Marketing</a></li>-->
        <!--                </ul>-->

        <!--              </div>&lt;!&ndash; End sidebar tags&ndash;&gt;-->

    </div><!-- End sidebar -->

</div><!-- End blog sidebar -->

itobj/templates/itobj/show_title_stats.html
{% load hitcount_tags %}

<h2 class="entry-title">
    <a href="{{ p.get_absolute_url }}">{{p.title}}</a>
</h2>

<div class="entry-meta">
    <ul>
        <li class="d-flex align-items-center"><i class="icofont-list"></i> <a>{{p.cat}}</a></li>
        <li class="d-flex align-items-center"><i class="icofont-user"></i> <a>Kirill Netreba</a></li>
        <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a>
            <time datetime="{{p.time_update}}">{{p.time_update|date:"M d, Y"}}</time></a></li>
        <li class="d-flex align-items-center"><a href="{% url 'like_post' p.slug %}">
        {% if liked %}
            <i class="icofont-heart" style="color:red"></i>
        {% else %}
            <i class="icofont-heart"></i>
        {% endif %}
        </a> <a>{{ p.total_likes }}</a></li>
        <li class="d-flex align-items-center"><i class="icofont-money-bag"></i> <a>{{p.trending}}</a></li>
        <li class="d-flex align-items-center"><i class="icofont-eye"></i> <a>{% get_hit_count for p %}</a></li>
    </ul>
</div>